import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { NODE_KIND_DESCRIPTIONS } from '../../../src/schema/node.js';
import { EDGE_KIND_DESCRIPTIONS } from '../../../src/schema/edge.js';
import { SourceManifestSchema, type SourceManifest } from '../../../src/schema/source_manifest.js';

/**
 * Prepended to every generated `.js` data file so editors and the project
 * type-check skip them — they are emitted artifacts, not hand-written source.
 */
const TS_NOCHECK_BANNER = '// @ts-nocheck\n';

const readJsonl = (path: string): unknown[] => readFileSync(path, 'utf8')
	.split('\n')
	.filter((line) => line.trim().length > 0)
	.map((line) => JSON.parse(line) as unknown);

/**
 * Writes the static node/edge kind descriptions (the single source of truth in
 * `src/schema`) to `web/js_autogenerated/kind_descriptions.js`. This file is committed and
 * independent of any loaded graph, so the legend tooltips work on every load
 * path — embedded data, fetched JSONL, or drag-and-drop — without a rebuild.
 */
const writeKindDescriptions = (dataDir: string): void => {
	const payload = { nodes: NODE_KIND_DESCRIPTIONS, edges: EDGE_KIND_DESCRIPTIONS };
	const outPath = join(dataDir, 'kind_descriptions.js');
	const banner = `${TS_NOCHECK_BANNER}// Generated from src/schema by scripts/build-data.ts. Do not edit by hand.\n`;
	writeFileSync(outPath, `${banner}window.KIND_DESCRIPTIONS = ${JSON.stringify(payload, null, '\t')};\n`);
	console.log(`✓ ${Object.keys(NODE_KIND_DESCRIPTIONS).length} node + ${Object.keys(EDGE_KIND_DESCRIPTIONS).length} edge descriptions -> ${outPath}`);
};

/**
 * Reads the source provenance `extract` wrote to `<graphDir>/source.json`, or
 * `undefined` when the file is absent or malformed. When present it is emitted as
 * `window.GRAPH_SOURCE`, letting the static page deep-link every node to its
 * declaration on GitHub — the same behaviour the `webview` command provides live.
 */
const readSourceManifest = (graphDir: string): SourceManifest | undefined => {
	const path = join(graphDir, 'source.json');
	if (existsSync(path) === false) {
		return undefined;
	}
	try {
		const parsed = SourceManifestSchema.safeParse(JSON.parse(readFileSync(path, 'utf8')));
		return parsed.success === true ? parsed.data : undefined;
	} catch {
		return undefined;
	}
};

const main = (): void => {
	const here = fileURLToPath(new URL('.', import.meta.url));
	const graphDir = process.argv[2] === undefined
		? join(here, '..', '..', '..', '.ts_knowledge_graph', 'graph')
		: process.argv[2];

	const nodes = readJsonl(join(graphDir, 'nodes.jsonl'));
	const edges = readJsonl(join(graphDir, 'edges.jsonl'));
	const source = readSourceManifest(graphDir);

	const dataDir = join(here, '..', 'web', 'js_autogenerated');
	const outPath = join(dataDir, 'graph_data.js');
	const sourceScript = source === undefined
		? ''
		: `window.GRAPH_SOURCE = ${JSON.stringify({ github: source })};\n`;
	writeFileSync(outPath, `${TS_NOCHECK_BANNER}${sourceScript}window.GRAPH_DATA = ${JSON.stringify({ nodes, edges })};\n`);
	console.log(`✓ ${nodes.length} nodes, ${edges.length} edges -> ${outPath}`);
	if (source !== undefined) {
		console.log(`✓ source ${source.baseUrl} @ ${source.commit.slice(0, 7)} — nodes deep-link to GitHub`);
	}

	writeKindDescriptions(dataDir);
};

main();
