import { SourceManifest } from '../schema/source_manifest.js';
import { GraphReportData, RankedSymbol, ReportSymbol } from './report_data.js';

/** The text formats {@link GraphReport.render} produces directly. PDF is derived from the visual HTML by the command. */
export type ReportFormat = 'markdown' | 'json';

/** The tool's own repository, linked from the report footer. */
const TOOL_REPO_URL = 'https://github.com/jeromeetienne/ts_knowledge_graph';

/**
 * Renders a {@link GraphReportData} to a string. Pure: the same data object maps
 * deterministically to markdown, JSON, or the self-contained visual HTML the PDF
 * path is built from — no store access, no clock, no filesystem — which keeps
 * every format unit-testable in isolation. Mirrors how {@link CommunityDetector}
 * is the pure core that {@link GraphClusterer} wraps with I/O.
 */
export class GraphReport {
	static render(data: GraphReportData, format: ReportFormat): string {
		if (format === 'json') {
			return JSON.stringify(data, null, 2);
		}
		return GraphReport.renderMarkdown(data);
	}

	/** The GitHub permalink for a symbol, or null when the graph recorded no source provenance. */
	static permalink(provenance: SourceManifest | null, symbol: ReportSymbol): string | null {
		if (provenance === null) {
			return null;
		}
		return `${provenance.baseUrl}/blob/${provenance.commit}/${provenance.prefix}${symbol.filePath}#L${symbol.startLine}`;
	}

	/**
	 * A location cell: a markdown link to the symbol on GitHub when source
	 * provenance was recorded, falling back to a plain `path:line` code span.
	 */
	private static location(provenance: SourceManifest | null, symbol: ReportSymbol): string {
		const label = `\`${symbol.filePath}:${symbol.startLine}\``;
		const link = GraphReport.permalink(provenance, symbol);
		return link === null ? label : `[${label}](${link})`;
	}

	private static renderMarkdown(data: GraphReportData): string {
		const lines: string[] = [];
		lines.push(`# Codebase brief — ${data.project}`, '');
		lines.push(GraphReport.provenanceLine(data), '');
		lines.push(GraphReport.banner(data), '');
		lines.push(`> ${data.verdict}`, '');

		lines.push('## Snapshot', '', GraphReport.snapshotLine(data), '');

		lines.push('## Composition', '');
		lines.push('**Symbols by kind**', '', ...GraphReport.kindTable(data.nodeKinds), '');
		lines.push('**Relationships by kind**', '', ...GraphReport.kindTable(data.edgeKinds), '');

		lines.push('## Load-bearing code', '');
		lines.push('**Most depended-upon** — direct callers', '');
		lines.push(...GraphReport.rankSection(data.hubsByCallers, 'Callers', 'No call edges — run `extract --semantic`.', data.provenance), '');
		lines.push('**Largest blast radius** — symbols transitively affected by a change', '');
		lines.push(...GraphReport.rankSection(data.hubsByBlastRadius, 'Impacted', 'No call edges — run `extract --semantic`.', data.provenance), '');

		lines.push('## Communities', '');
		lines.push(...GraphReport.communitySection(data), '');

		lines.push('## Runtime', '');
		lines.push(...GraphReport.runtimeSection(data), '');

		if (data.enriched === true) {
			lines.push('## Structure vs. runtime', '');
			lines.push(...GraphReport.structureSection(data.structureVsRuntime), '');
		}

		lines.push('## Cycles', '');
		lines.push(...GraphReport.cycleSection(data), '');

		lines.push('## System boundary', '');
		lines.push(...GraphReport.boundarySection(data), '');

		lines.push('## Cleanup candidates', '');
		lines.push(...GraphReport.deadExportSection(data), '');

		lines.push('## Where to go next', '');
		lines.push(...GraphReport.nextStepsSection(data), '');

		lines.push(`*Generated by [ts-knowledge-graph](${TOOL_REPO_URL})*`, '');
		return lines.join('\n');
	}

	private static provenanceLine(data: GraphReportData): string {
		const parts: string[] = [];
		if (data.provenance !== null) {
			if (data.provenance.prefix.length > 0) {
				parts.push(`\`${data.provenance.prefix}\``);
			}
			parts.push(`commit \`${data.provenance.commit.slice(0, 7)}\``);
		}
		parts.push(`generated ${data.generatedAt}`);
		return parts.join(' · ');
	}

	private static banner(data: GraphReportData): string {
		const semantic = `semantic ${data.semantic === true ? '✓' : '—'}`;
		const enriched = `enriched ${data.enriched === true ? '✓' : '—'}`;
		const coverage = data.coverage === null ? '' : ` · runtime coverage ${GraphReport.pct0(data.coverage)}`;
		return `**${semantic} · ${enriched}${coverage}**`;
	}

	private static snapshotLine(data: GraphReportData): string {
		const quality = data.communityQuality === null ? '' : ` (quality ${data.communityQuality.toFixed(2)})`;
		return [
			`${data.totals.symbols} symbols`,
			`${data.totals.files} files`,
			`${data.totals.relationships} relationships`,
			`${data.totals.communities} communities${quality}`,
			`${data.totals.deadExports} dead exports`,
			`${data.totals.cycles} cycles`,
		].join(' · ');
	}

	private static kindTable(kinds: { kind: string; count: number }[]): string[] {
		if (kinds.length === 0) {
			return ['_(none)_'];
		}
		return GraphReport.table(['Kind', 'Count'], kinds.map((entry) => [`\`${entry.kind}\``, String(entry.count)]), ['left', 'right']);
	}

	private static rankSection(items: RankedSymbol[], scoreHeader: string, empty: string, provenance: SourceManifest | null): string[] {
		if (items.length === 0) {
			return [`_${empty}_`];
		}
		return GraphReport.table(
			['Symbol', scoreHeader, 'Location'],
			items.map((item) => [`\`${item.name}\``, String(item.score), GraphReport.location(provenance, item)]),
			['left', 'right', 'left'],
		);
	}

	private static communitySection(data: GraphReportData): string[] {
		if (data.communities.length === 0) {
			return ['_No communities assigned — run `cluster` to populate._'];
		}
		return GraphReport.table(['Community', 'Size'], data.communities.map((community) => [GraphReport.cell(community.label), String(community.size)]), ['left', 'right']);
	}

	private static runtimeSection(data: GraphReportData): string[] {
		if (data.enriched === false) {
			return ['_Run `enrich` to populate the runtime sections (hotspots, cost, structure-vs-runtime)._'];
		}
		const lines: string[] = [];
		lines.push('**Hotspots** — exclusive self-time', '');
		lines.push(...GraphReport.table(
			['Symbol', 'Self-time (ms)', 'Location'],
			data.hotspots.map((hotspot) => [`\`${hotspot.name}\``, hotspot.score.toFixed(1), GraphReport.location(data.provenance, hotspot)]),
			['left', 'right', 'left'],
		), '');
		lines.push('**Cost** — inclusive, share of total runtime', '');
		lines.push(...GraphReport.table(
			['Symbol', 'Inclusive (ms)', 'Share', 'Location'],
			data.cost.map((node) => [
				`\`${node.name}\`${node.cyclic === true ? ' ↺' : ''}`,
				node.inclusiveCost.toFixed(1),
				GraphReport.pct1(node.shareOfTotal),
				GraphReport.location(data.provenance, node),
			]),
			['left', 'right', 'right', 'left'],
		));
		return lines;
	}

	private static structureSection(structure: GraphReportData['structureVsRuntime']): string[] {
		return [
			GraphReport.groupLine('Orchestrators', 'high inclusive cost, ~0 self — optimize their callees', structure.orchestrators),
			GraphReport.groupLine('Hidden hotspots', 'hot, but few callers — easy to miss in review', structure.hiddenHotspots),
			GraphReport.groupLine('Aligned core', 'most depended-upon and hottest — genuine hotspots', structure.alignedCore),
		];
	}

	private static groupLine(title: string, description: string, members: ReportSymbol[]): string {
		const names = members.length === 0 ? '—' : members.map((member) => `\`${member.name}\``).join(', ');
		return `- **${title}** (${description}): ${names}`;
	}

	private static cycleSection(data: GraphReportData): string[] {
		if (data.cycles.length === 0) {
			return ['_No call cycles detected — the call graph is acyclic._'];
		}
		return data.cycles.map((cycle) => `- ${cycle.size}-symbol cycle: ${cycle.members.map((member) => `\`${member.name}\``).join(', ')}`);
	}

	private static boundarySection(data: GraphReportData): string[] {
		const { endpoints, configFlags, externalApis } = data.boundary;
		if (endpoints.length === 0 && configFlags.length === 0 && externalApis.length === 0) {
			return ['_No endpoints, configuration flags, or external API calls detected._'];
		}
		const lines: string[] = [];
		const list = (label: string, items: ReportSymbol[]): void => {
			if (items.length > 0) {
				lines.push(`- **${label}** (${items.length}): ${items.map((item) => `\`${item.name}\``).join(', ')}`);
			}
		};
		list('Endpoints', endpoints);
		list('Configuration flags', configFlags);
		list('External APIs', externalApis);
		return lines;
	}

	private static deadExportSection(data: GraphReportData): string[] {
		if (data.deadExports.length === 0) {
			return ['_No dead exports._'];
		}
		return [
			'Exported but never referenced:',
			'',
			...GraphReport.table(
				['Symbol', 'Kind', 'Location'],
				data.deadExports.map((symbol) => [`\`${symbol.name}\``, symbol.kind, GraphReport.location(data.provenance, symbol)]),
			),
		];
	}

	private static nextStepsSection(data: GraphReportData): string[] {
		const commands: string[] = [];
		if (data.enriched === true) {
			commands.push('# rank where runtime is spent, and who is responsible for it', `ts-knowledge-graph hotspots -o ${data.outputFolder}`, `ts-knowledge-graph cost -o ${data.outputFolder}`);
		} else if (data.hubsByBlastRadius.length > 0) {
			commands.push('# the highest-impact symbols to change carefully', `ts-knowledge-graph hotspots --by blast-radius -o ${data.outputFolder}`);
		}
		if (data.deadExports.length > 0) {
			commands.push('# confirm dead code before deleting', `ts-knowledge-graph dead-exports -o ${data.outputFolder}`);
		}
		commands.push('# explore the whole graph interactively', `ts-knowledge-graph webview -o ${data.outputFolder}`);

		const lines = ['```sh', ...commands, '```'];
		const focus = data.enriched === true && data.hotspots.length > 0 ? data.hotspots[0] : data.hubsByBlastRadius[0];
		const link = focus === undefined ? null : GraphReport.permalink(data.provenance, focus);
		if (link !== null) {
			const label = data.enriched === true ? 'Hottest symbol' : 'Highest-impact symbol';
			lines.push('', `${label} on GitHub: [\`${focus.name}\`](${link})`);
		}
		return lines;
	}

	private static table(headers: string[], rows: string[][], align: ('left' | 'right')[] = []): string[] {
		const head = `| ${headers.join(' | ')} |`;
		const separator = `| ${headers.map((_, index) => (align[index] === 'right' ? '---:' : '---')).join(' | ')} |`;
		const body = rows.map((row) => `| ${row.map(GraphReport.cell).join(' | ')} |`);
		return [head, separator, ...body];
	}

	/** Escapes the pipe character so a symbol name never breaks a markdown table row. */
	private static cell(value: string): string {
		return value.replace(/\|/g, '\\|');
	}

	private static pct0(value: number): string {
		return `${(value * 100).toFixed(0)}%`;
	}

	private static pct1(value: number): string {
		return `${(value * 100).toFixed(1)}%`;
	}

	/**
	 * Renders a self-contained, print-ready HTML document for the same data — the
	 * substrate the `pdf` format is converted from, and a usable artifact on its own.
	 * Light theme, system fonts, inline styles, CSS-only bar charts: no external
	 * assets, so it renders identically offline and in a headless browser.
	 */
	static renderVisualHtml(data: GraphReportData): string {
		const esc = GraphReport.escapeHtml;
		const badge = (label: string, on: boolean): string =>
			`<span class="badge ${on === true ? 'ok' : 'off'}">${esc(label)} ${on === true ? '✓' : '—'}</span>`;
		const coverageBadge = data.coverage === null ? '' : `<span class="badge info">coverage ${GraphReport.pct0(data.coverage)}</span>`;

		const metric = (label: string, value: string): string =>
			`<div class="metric"><div class="metric-label">${esc(label)}</div><div class="metric-value">${esc(value)}</div></div>`;

		const maxSelf = data.hotspots.reduce((max, hotspot) => Math.max(max, hotspot.score), 0);
		const bar = (label: string, value: string, fraction: number, color: string): string =>
			`<div class="bar-row"><span class="bar-name">${esc(label)}</span>`
			+ `<span class="bar-track"><span class="bar-fill" style="width:${Math.min(100, Math.max(0, fraction * 100)).toFixed(1)}%;background:${color}"></span></span>`
			+ `<span class="bar-val">${esc(value)}</span></div>`;

		const sections: string[] = [];

		sections.push(`<header><h1>Codebase brief — ${esc(data.project)}</h1>`
			+ `<p class="sub">${esc(GraphReport.htmlProvenance(data))}</p>`
			+ `<p class="badges">${badge('semantic', data.semantic)} ${badge('enriched', data.enriched)} ${coverageBadge}</p>`
			+ `<p class="verdict">${esc(data.verdict)}</p></header>`);

		sections.push('<div class="metrics">'
			+ metric('symbols', String(data.totals.symbols))
			+ metric('files', String(data.totals.files))
			+ metric('relationships', String(data.totals.relationships))
			+ metric('communities', String(data.totals.communities))
			+ metric('dead exports', String(data.totals.deadExports))
			+ metric('cycles', String(data.totals.cycles))
			+ '</div>');

		if (data.enriched === true && data.cost.length > 0) {
			const rows = data.cost.map((node) => bar(node.name, `${GraphReport.pct1(node.shareOfTotal)}`, node.shareOfTotal, '#185FA5')).join('');
			sections.push(`<section><h2>Inclusive cost — share of total runtime</h2>${rows}</section>`);
		}
		if (data.enriched === true && data.hotspots.length > 0) {
			const rows = data.hotspots.map((hotspot) => bar(hotspot.name, `${hotspot.score.toFixed(1)} ms`, maxSelf > 0 ? hotspot.score / maxSelf : 0, '#854F0B')).join('');
			sections.push(`<section><h2>Self-time — exclusive milliseconds</h2>${rows}</section>`);
		}
		if (data.enriched === true) {
			const card = (title: string, description: string, members: ReportSymbol[], tone: string): string =>
				`<div class="svr ${tone}"><div class="svr-title">${esc(title)}</div>`
				+ `<div class="svr-members">${members.length === 0 ? '—' : members.map((member) => esc(member.name)).join(' · ')}</div>`
				+ `<div class="svr-note">${esc(description)}</div></div>`;
			sections.push('<section><h2>Structure vs. runtime</h2><div class="svr-grid">'
				+ card('Orchestrators', 'high inclusive cost, ~0 self — optimize their callees', data.structureVsRuntime.orchestrators, 'neutral')
				+ card('Hidden hotspots', 'hot, but few callers — easy to miss', data.structureVsRuntime.hiddenHotspots, 'warn')
				+ card('Aligned core', 'central and hot — genuine hotspots', data.structureVsRuntime.alignedCore, 'ok')
				+ '</div></section>');
		}

		if (data.deadExports.length > 0) {
			const rows = data.deadExports.map((symbol) =>
				`<tr><td class="mono">${esc(symbol.name)}</td><td>${esc(symbol.kind)}</td><td class="mono dim">${esc(`${symbol.filePath}:${symbol.startLine}`)}</td></tr>`).join('');
			sections.push(`<section><h2>Dead exports</h2><table><thead><tr><th>Symbol</th><th>Kind</th><th>Location</th></tr></thead><tbody>${rows}</tbody></table></section>`);
		}

		return GraphReport.htmlDocument(data.project, sections.join(''));
	}

	private static htmlProvenance(data: GraphReportData): string {
		const parts: string[] = [];
		if (data.provenance !== null) {
			parts.push(`${data.provenance.baseUrl.replace(/^https?:\/\//, '')}`);
			parts.push(`commit ${data.provenance.commit.slice(0, 7)}`);
		}
		parts.push(`generated ${data.generatedAt}`);
		return parts.join(' · ');
	}

	private static htmlDocument(title: string, body: string): string {
		const style = [
			'*{box-sizing:border-box}',
			'body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;color:#1b1b1a;background:#fff;max-width:820px;margin:0 auto;padding:40px 32px;line-height:1.5}',
			'h1{font-size:24px;font-weight:600;margin:0}',
			'h2{font-size:15px;font-weight:600;color:#5f5e5a;margin:28px 0 12px;text-transform:none}',
			'.sub{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;color:#888780;margin:4px 0 12px}',
			'.badges{margin:0 0 14px}',
			'.badge{display:inline-block;font-size:12px;padding:3px 9px;border-radius:6px;margin-right:6px}',
			'.badge.ok{background:#E1F5EE;color:#0F6E56}.badge.off{background:#F1EFE8;color:#5F5E5A}.badge.info{background:#E6F1FB;color:#185FA5}',
			'.verdict{font-size:15px;background:#F1EFE8;border-radius:10px;padding:12px 14px;margin:0}',
			'.metrics{display:flex;flex-wrap:wrap;gap:10px;margin:18px 0}',
			'.metric{background:#F1EFE8;border-radius:8px;padding:10px 14px;min-width:96px}',
			'.metric-label{font-size:12px;color:#5f5e5a}.metric-value{font-size:22px;font-weight:600}',
			'.bar-row{display:flex;align-items:center;gap:10px;margin:6px 0}',
			'.bar-name{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px;width:190px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
			'.bar-track{flex:1;height:9px;background:#F1EFE8;border-radius:999px;overflow:hidden}',
			'.bar-fill{display:block;height:100%}',
			'.bar-val{font-size:12px;color:#5f5e5a;width:74px;text-align:right}',
			'.svr-grid{display:flex;gap:10px;flex-wrap:wrap}',
			'.svr{flex:1;min-width:200px;border-radius:10px;padding:12px}',
			'.svr.neutral{background:#F1EFE8}.svr.warn{background:#FAEEDA}.svr.ok{background:#E1F5EE}',
			'.svr-title{font-size:13px;font-weight:600;margin-bottom:6px}',
			'.svr-members{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;margin-bottom:6px}',
			'.svr-note{font-size:12px;color:#5f5e5a}',
			'table{width:100%;border-collapse:collapse;font-size:13px}',
			'th{text-align:left;color:#5f5e5a;font-weight:500;border-bottom:1px solid #D3D1C7;padding:6px 8px}',
			'td{padding:6px 8px;border-bottom:1px solid #F1EFE8}',
			'.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.dim{color:#888780}',
			'footer{margin-top:32px;font-size:12px;color:#888780}',
		].join('');
		return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Codebase brief — ${GraphReport.escapeHtml(title)}</title><style>${style}</style></head>`
			+ `<body>${body}<footer>Generated by <a href="${TOOL_REPO_URL}">ts-knowledge-graph</a></footer></body></html>`;
	}

	private static escapeHtml(value: string): string {
		return value
			.replace(/&/g, '&amp;')
			.replace(/</g, '&lt;')
			.replace(/>/g, '&gt;')
			.replace(/"/g, '&quot;');
	}
}
