// @ts-check
import { state } from './app_state.js';
import { Dom } from './dom.js';
import { Folds } from './folds.js';
import { Theme } from './theme.js';
import { Legends } from './legends.js';
import { Graph } from './graph.js';
import { Selection } from './selection.js';
import { Search } from './search.js';

/* Register the fcose layout extension (loaded as a CDN global, see index.html) so the
   label-aware force layout is selectable. Guarded so a missing script never breaks the viewer. */
if (window.cytoscapeFcose !== undefined) {
	cytoscape.use(window.cytoscapeFcose);
}

/**
 * Entry point: wires the static controls, then loads the graph from the embedded
 * `window.GRAPH_DATA`, a same-origin fetch of the JSONL files, or drag-and-drop.
 */
class DataLoading {
	static boot() {
		DataLoading.setupDropzone();
		Folds.setupFolds();
		Folds.setupSectionHelp();
		Theme.setupTheme();
		Dom.el('hide-isolated').addEventListener('change', (event) => {
			state.hideIsolated = Dom.asInput(event.target).checked;
			Legends.applyFilters();
		});
		Dom.el('relayout').addEventListener('click', () => Graph.runLayout());
		Dom.el('encoding-select').addEventListener('change', (event) => {
			state.encoding = Graph.encodingFromValue(Dom.asSelect(event.target).value);
			if (state.cy !== undefined) {
				state.cy.style(Graph.cyStyle());
			}
		});
		Dom.el('only-measured').addEventListener('change', (event) => {
			state.onlyMeasured = Dom.asInput(event.target).checked;
			Legends.applyFilters();
		});
		Dom.el('search').addEventListener('input', () => Search.renderSearchResults());
		Dom.el('search').addEventListener('keydown', (event) => {
			if (event.key === 'Enter') {
				const first = /** @type {HTMLElement | null} */ (document.querySelector('#search-results .hit'));
				if (first !== null) {
					first.click();
				}
			}
		});
		Dom.el('nav-back').addEventListener('click', () => Selection.navigateHistory(-1));
		Dom.el('nav-forward').addEventListener('click', () => Selection.navigateHistory(1));

		if (window.GRAPH_DATA !== undefined) {
			Graph.setData(window.GRAPH_DATA.nodes, window.GRAPH_DATA.edges, 'embedded graph_data.js');
			return;
		}
		if (location.protocol.startsWith('http') === true) {
			DataLoading.tryFetch();
			return;
		}
		Dom.el('status').textContent = 'no data — run `npm run build`, or drop the JSONL files here';
	}

	static async tryFetch() {
		try {
			const [nodesText, edgesText] = await Promise.all([
				fetch('../../../.ts_knowledge_graph/graph/nodes.jsonl').then((r) => r.ok === true ? r.text() : Promise.reject(new Error(String(r.status)))),
				fetch('../../../.ts_knowledge_graph/graph/edges.jsonl').then((r) => r.ok === true ? r.text() : Promise.reject(new Error(String(r.status)))),
			]);
			Graph.setData(DataLoading.parseJsonl(nodesText), DataLoading.parseJsonl(edgesText), 'fetched ../../../.ts_knowledge_graph/graph/*.jsonl');
		} catch {
			Dom.el('status').textContent = 'no data — generate js_autogenerated/graph_data.js or drop the JSONL files here';
		}
	}

	/**
	 * Parses newline-delimited JSON into records. The records cross an untyped
	 * deserialisation boundary, so callers narrow them via the `setData` signature.
	 * @param {string} text
	 * @returns {any[]}
	 */
	static parseJsonl(text) {
		return text.split('\n').filter((line) => line.trim().length > 0).map((line) => JSON.parse(line));
	}

	static setupDropzone() {
		const zone = Dom.el('dropzone');
		window.addEventListener('dragover', (event) => {
			event.preventDefault();
			zone.classList.add('active');
		});
		window.addEventListener('dragleave', (event) => {
			if (event.relatedTarget === null) {
				zone.classList.remove('active');
			}
		});
		window.addEventListener('drop', async (event) => {
			event.preventDefault();
			zone.classList.remove('active');
			if (event.dataTransfer === null) {
				return;
			}
			for (const file of event.dataTransfer.files) {
				const records = DataLoading.parseJsonl(await file.text());
				if (records.length === 0) {
					continue;
				}
				if (records[0].from !== undefined && records[0].to !== undefined) {
					state.droppedFiles.edges = records;
				} else {
					state.droppedFiles.nodes = records;
				}
			}
			if (state.droppedFiles.nodes !== undefined && state.droppedFiles.edges !== undefined) {
				Graph.setData(state.droppedFiles.nodes, state.droppedFiles.edges, 'dropped files');
			} else {
				Dom.el('status').textContent = 'got one file — drop the other one too';
			}
		});
	}
}

DataLoading.boot();
