// @ts-check
/** @import { KindDescriptions } from '../../types/app_globals.js' */

/**
 * Shared constants for the viewer: the node/edge colour palettes, the runtime
 * heat ramp, localStorage keys, and small lookup tables. Pure data, imported by
 * the render modules.
 */

/** @type {Record<string, string>} */
export const NODE_COLORS = {
	Module: '#4f8cff',
	Class: '#f59e0b',
	Interface: '#a78bfa',
	TypeAlias: '#34d399',
	Enum: '#f472b6',
	Function: '#fb923c',
	Method: '#facc15',
	Property: '#94a3b8',
	Parameter: '#64748b',
	Variable: '#2dd4bf',
	ExternalModule: '#6b7280',
	ConfigFlag: '#84cc16',
	ExternalAPI: '#fb7185',
	Endpoint: '#38bdf8',
};

/** @type {Record<string, string>} */
export const EDGE_COLORS = {
	CONTAINS: '#475569',
	IMPORTS: '#64748b',
	EXPORTS: '#64748b',
	CALLS: '#ef4444',
	INSTANTIATES: '#f97316',
	EXTENDS: '#8b5cf6',
	IMPLEMENTS: '#a78bfa',
	USES_TYPE: '#10b981',
	RETURNS: '#14b8a6',
	PARAM_TYPE: '#06b6d4',
	READS: '#eab308',
	WRITES: '#eab308',
	OVERRIDES: '#94a3b8',
	READS_CONFIG: '#65a30d',
	CALLS_EXTERNAL: '#e11d48',
	HANDLES: '#0ea5e9',
	CALLS_RUNTIME: '#be123c',
};

/* One-line descriptions per node/edge kind, generated from src/schema into
   js_autogenerated/kind_descriptions.js. Absent (empty) when that file has not been built. */
/** @type {KindDescriptions} */
export const KIND_DESCRIPTIONS = window.KIND_DESCRIPTIONS ?? { nodes: {}, edges: {} };

/* Heat ramp for runtime self-time: cool slate → yellow → red ("red = hot"). */
export const HEAT_STOPS = [
	{ at: 0, color: [100, 116, 139] },
	{ at: 0.5, color: [253, 224, 71] },
	{ at: 1, color: [220, 38, 38] },
];

export const HOTSPOTS_LIMIT = 12;

/* Communities shown in the legend before the rest collapse behind a "more" toggle. */
export const COMMUNITIES_VISIBLE_LIMIT = 12;

/* Dwell, in milliseconds, before a hovered graph node reveals its tooltip. */
export const HOVER_TOOLTIP_DELAY_MS = 1000;

/* Persisted theme override ('light' | 'dark'); absent means follow the OS. */
export const THEME_STORAGE_KEY = 'ktg.theme';

/* Persisted collapsed-by-key map for the foldable sidebar sections. */
export const FOLD_STORAGE_KEY = 'ktg.sidebar.folds';

/* Persisted collapsed flag ('true' | 'false') for the whole left sidebar. */
export const SIDEBAR_STORAGE_KEY = 'ktg.sidebar.collapsed';

/* Shared prefix for every persisted viewer preference; the Reset view control clears all keys under it. */
export const STORAGE_PREFIX = 'ktg.';

/* Real source files we can link to GitHub; external modules, `process.env`, and API hosts carry synthetic paths. */
export const SOURCE_FILE_PATTERN = /\.(?:tsx?|mts|cts|jsx?|mjs|cjs)$/;

export const ESCAPE_REPLACEMENTS = /** @type {Record<string, string>} */ ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' });
